version: 2

models:
  - name: stg_municipalities
    config:
      contract:
        enforced: true
    description: >
      Staging table about the municipalities where Carris Metropolitana has service.
    columns:
      - name: municipality_id
        description: Unique identifier for municipality.
        data_type: string
        data_tests:
          - not_null
          - unique
      - name: municipality_name
        description: Name of municipality.
        data_type: string
        data_tests:
          - not_null
      - name: district_id
        description: Unique identifier for district.
        data_type: string
        data_tests:
          - not_null
      - name: district_name
        description: Name of district.
        data_type: string
        data_tests:
          - not_null
      - name: region_id
        description: Unique identifier for region.
        data_type: string
        data_tests:
          - not_null
      - name: region_name
        description: Name of region.
        data_type: string
        data_tests:
          - not_null
      - name: municipality_prefix
        description: Prefix municipality.
        data_type: string
        data_tests:
          - not_null
      - name: ingestion_date
        description: Date when the data was ingested.
        data_type: date
        data_tests:
          - not_null
#      - name: partition_date
#        description: Date when the data was partitioned.
#        data_type: date
#        data_tests:
#          - not_null

  - name: stg_gtfs_stops
    config:
      contract:
        enforced: true
    description: >
      Staging table with information about the different stops from gtfs file.
    columns:
      - name: stop_id
        description: Unique identifier for the stop
        data_type: string
        data_tests:
          - not_null
      - name: stop_name
        description: Name of the stop
        data_type: string
      - name: short_name
        description: Short name of the stop
        data_type: string
      - name: district_id
        description: ID of the district
        data_type: string
      - name: municipality_id
        description: ID of the municipality
        data_type: string
      - name: region_id
        description: ID of the region
        data_type: string
      - name: district_name
        description: Name of the district
        data_type: string
      - name: municipality_name
        description: Name of the municipality
        data_type: string
      - name: region_name
        description: Name of the region
        data_type: string
      - name: latitude
        description: Latitude of the stop
        data_type: string
      - name: longitude
        description: Longitude of the stop
        data_type: string
      - name: facilities
        description: List of facilities at the stop
        data_type: string
      - name: lines
        description: List of lines that pass through the stop
        data_type: string
      - name: localities
        description: Localities covered by the stop
        data_type: string
      - name: operational_status
        description: Current operational status
        data_type: string
      - name: patterns
        description: Patterns associated with the stop
        data_type: string
      - name: routes
        description: Routes associated with the stop
        data_type: string
      - name: tts_name
        description: Text-to-speech name
        data_type: string
      - name: wheelchair_boarding
        description: Accessibility status for wheelchair boarding
        data_type: string
      - name: ingestion_date
        description: Date when the data was ingested
        data_type: date
        data_tests:
          - not_null
