[tool.poetry]
name = "data-engineering-prj-final"
version = "1.0.0"
description = "Data Engineering - Final Project"
authors = [
  "Michel Silva",
  "Telma Costa",
  "Pedro Rocha"
]
license = "MIT"
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
google-cloud-storage = "^2.16.0"
dbt-core = "^1.7.0"
dbt-bigquery = "^1.7.0"
python-dotenv = "^1.0.1"
pydantic = "^2.7.1"
loguru = "^0.7.2"
pyspark = "^3.5.1"
requests = "^2.32.2"
pandas = "^2.2.2"
pyarrow = "^16.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
flake8 = "^7.0.0"
black = "^24.4.2"
isort = "^5.13.2"
mypy = "^1.10.0"
pre-commit = "^3.7.1"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["."]

[tool.pre-commit]
hook-config = ".pre-commit-config.yaml"

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["google.cloud", "google"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
