version: 2

models:
  - name: dim_date
    description: Dimension table about the date.
    columns:
      - name: date_day
        description: Date.
      - name: prior_date_day
        description: Date of the previous day.
      - name: next_date_day
        description: Date of the next day.
      - name: prior_year_date_day
        description: Date of the same day in the previous year.
      - name: prior_year_over_year_date_day
        description: Date of the same day in the year before the previous year.
      - name: day_of_week
        description: Day of the week.
      - name: day_of_week_name
        description: Name of the day of the week.
      - name: day_of_week_name_short
        description: Short name of the day of the week.
      - name: day_of_month
        description: Day of the month.
      - name: day_of_year
        description: Day of the year.
      - name: week_start_date
        description: Start date of the week.
      - name: week_end_date
        description: End date of the week.
      - name: prior_year_week_start_date
        description: Start date of the week in the previous year.
      - name: prior_year_week_end_date
        description: End date of the week in the previous year.
      - name: week_of_year
        description: Week of the year.
      - name: iso_week_start_date
        description: Start date of the ISO week.
      - name: iso_week_end_date
        description: End date of the ISO week.
      - name: prior_year_iso_week_start_date
        description: Start date of the ISO week in the previous year.
      - name: prior_year_iso_week_end_date
        description: End date of the ISO week in the previous year.
      - name: iso_week_of_year
        description: ISO week of the year.
      - name: prior_year_week_of_year
        description: Week of the year in the previous year.
      - name: prior_year_iso_week_of_year
        description: ISO week of the year in the previous year.
      - name: month_of_year
        description: Month of the year.
      - name: month_name
        description: Name of the month.
      - name: month_name_short
        description: Short name of the month.
      - name: month_start_date
        description: Start date of the month.
      - name: month_end_date
        description: End date of the month.
      - name: prior_year_month_start_date
        description: Start date of the month in the previous year.
      - name: prior_year_month_end_date
        description: End date of the month in the previous year.
      - name: quarter_of_year
        description: Quarter of the year.
      - name: quarter_start_date
        description: Start date of the quarter.
      - name: quarter_end_date
        description: End date of the quarter.
      - name: year_number
        description: Year number.
      - name: year_start_date
        description: Start date of the year.
      - name: year_end_date
        description: End date of the year.
      - name: ingested_at
        description: Timestamp when the data was ingested.

  - name: dim_lines
    config:
      contract:
        enforced: true
    description: >
      Dimension table about the lines of carris service.
    columns:
      - name: line_id
        description: Unique identifier for line.
        data_type: string
        data_tests:
          - not_null
          - unique
      - name: line_name
        description: Name of line.
        data_type: string
        data_tests:
          - not_null

  - name: dim_municipalities
    config:
      contract:
        enforced: true
    description: >
      Dimension table about the municipalities where Carris Metropolitana has service.
    columns:
      - name: municipality_id
        description: Unique identifier for municipality.
        data_type: string
        data_tests:
          - not_null
          - unique
      - name: municipality_name
        description: Name of municipality.
        data_type: string
        data_tests:
          - not_null
      - name: district_id
        description: Unique identifier for district.
        data_type: string
        data_tests:
          - not_null
      - name: district_name
        description: Name of district.
        data_type: string
        data_tests:
          - not_null
      - name: region_id
        description: Unique identifier for region.
        data_type: string
        data_tests:
          - not_null
      - name: region_name
        description: Name of region.
        data_type: string
        data_tests:
          - not_null
      - name: municipality_prefix
        description: Prefix municipality.
        data_type: string
        data_tests:
          - not_null
      - name: ingestion_date
        description: Date when the data was ingested.
        data_type: date
        data_tests:
          - not_null
